name: Bug Report
description: Found something that is failing? File an issue so I can fix it
labels: [bug]
assignees:
  - markusand
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report. Please answer the following questions for yourself before submitting an issue.
        
        - [ ] I am running the latest version
        - [ ] I checked the documentation and found no answer
        - [ ] I checked the issues to make sure that it has not already been filed
  - type: input
    id: os
    attributes:
      label: OS & Browser
      description: "Which operating system and web brower are you using? Provide the version as well."
      placeholder: "macOS Monterrey 12.3.1 / Safari 15.4"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Detailed description
      description: Describe in as much detail as possible what happened. Attach screenshots if needed
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Explain what was supposed to happen.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide detailed steps for reproducing the issue.
      placeholder: |
        1. Step 1
        2. Step 2
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant console, network inspector or log output
